AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Create slack reminders using the new scheduler.

Globals:
  Function:
    Timeout: 6
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: slack-reminder
        LOG_LEVEL: INFO

Parameters:
  Email:
    Type: String
    Default: 'Send reminder to this email'
  SchedulerName:
    Type: String
    Default: 'slack-reminder-scheduler'


Resources:
  RemindMeFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: remind_me/
      Handler: app.handler
      Runtime: python3.9
      Role: !GetAtt CreateSchedulerLambdaRole.Arn
      Layers:
        - !Ref SharedLibsLayer
      Architectures:
        - arm64
      Environment:
        Variables:
          SCHEDULER_NAME: !Ref SchedulerName
          WEBHOOK_SNS_ARN: !Ref WebhookSNS
          SNS_PUBLISH_ROLE_ARN: !GetAtt PublishToWebhookSNSRole.Arn


  CreateSchedulerLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'scheduler:CreateSchedule'
                Resource: '*'
                
              - Effect: Allow
                Action: 'iam:PassRole'
                Resource: !GetAtt PublishToWebhookSNSRole.Arn
  
  WebhookSNS:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref Email
          Protocol: email 

        
  PublishToWebhookSNSRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - scheduler.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'sns:Publish'
                Resource: !Ref WebhookSNS

  SharedLibsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: app_layer
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9
